const FETCH_BEERS_START = 'FETCH_BEERS_START';
const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCES';
const FETCH_BEERS_FAIL = 'FETCH_BEERS_FAIL';

const LOAD_MORE_BEERS_START = 'LOAD_MORE_BEERS_START'
const LOAD_MORE_BEERS_SUCCESS = 'LOAD_MORE_BEERS_SUCCESS'
const LOAD_MORE_BEERS_FAIL = 'LOAD_MORE_BEERS_FAIL'

export {
    FETCH_BEERS_START,
    FETCH_BEERS_SUCCESS,
    FETCH_BEERS_FAIL,

    LOAD_MORE_BEERS_START,
    LOAD_MORE_BEERS_SUCCESS,
    LOAD_MORE_BEERS_FAIL
}