const FETCH_BEERS_START = 'FETCH_BEERS_START';
const FETCH_BEERS_SUCCES = 'FETCH_BEERS_SUCCES';
const FETCH_BEERS_FAIL = 'FETCH_BEERS_FAIL';

export {
    FETCH_BEERS_START,
    FETCH_BEERS_SUCCES,
    FETCH_BEERS_FAIL
}